name: hackatools
description: Simple tools to manage hackatons

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6+3
  cached_network_image: ^1.1.1
  connectivity: ^0.4.3+7
  image_picker: ^0.6.1+4
  font_awesome_flutter: ^8.4.0
  flutter_auth_buttons: ^0.5.0
  rxdart: ^0.22.0
  bloc_pattern: ^2.1.9+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sql/
    - assets/animations/